context:
  version: 2.12.21

package:
  name: scala2
  version: ${{ version }}

source:
  - url: https://github.com/scala/scala/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 2f77be2791275ba2b5d5309e8222e38d613b72bbd317981ca64f64c991257a1d

build:
  number: 0
  noarch: generic

requirements:
  build:
    - maven
    - sbt
    - sed
    - openjdk =11
  run:
    # from https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html
    - openjdk >=11,<=25

tests:
  - script:
      - scala -help
      - scala -version
      - ${SCALA_HOME}/bin/scala -help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - target/generated-resources/licenses/
  summary: Scala 2 compiler and standard library.
  homepage: https://scala-lang.org
  repository: https://github.com/scala/scala

extra:
  recipe-maintainers:
    - alberto-scolari
